"""after add lock features

Revision ID: 936c8932f68d
Revises: c79e292181cf
Create Date: 2026-02-08 18:22:53.491675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '936c8932f68d'
down_revision: Union[str, None] = 'c79e292181cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('is_locked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_locked')
    op.drop_column('users', 'failed_login_attempts')
    # ### end Alembic commands ###
